name: PR Check

on:
  pull_request:
    branches: [ "master", "main" ]

jobs:
  test:
    name: Run Unit Tests & Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # 1. Odtwarzamy google-services.json
      - name: Restore google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo "$GOOGLE_SERVICES_JSON" > app/google-services.json

      # 2. Generujemy brakujÄ…cy web_client_id w nowym pliku secrets.xml
      - name: Generate Auth Secrets
        env:
          WEB_CLIENT_ID: ${{ secrets.WEB_CLIENT_ID }}
        run: |
          mkdir -p auth/src/main/res/values
          echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>" > auth/src/main/res/values/secrets.xml
          echo "<resources>" >> auth/src/main/res/values/secrets.xml
          echo "    <string name=\"web_client_id\">$WEB_CLIENT_ID</string>" >> auth/src/main/res/values/secrets.xml
          echo "</resources>" >> auth/src/main/res/values/secrets.xml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Run Lint
        run: ./gradlew lintDebug
