name: Release to Play Store

on:
  workflow_dispatch: # Uruchamianie ręczne przyciskiem

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Wymagane, zeby CI mogl zrobic commit ze zmieniona wersja

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Uzywamy tokenu, zeby pushowac zmiany

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 1. Odtwarzanie plikow konfiguracyjnych i kluczy
      - name: Restore google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > app/google-services.json

      - name: Decode Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_FILE }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > app/keystore.jks

      # 2. Generujemy brakujący web_client_id w nowym pliku secrets.xml
      - name: Generate Auth Secrets
        env:
          WEB_CLIENT_ID: ${{ secrets.WEB_CLIENT_ID }}
        run: |
          mkdir -p auth/src/main/res/values
          echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>" > auth/src/main/res/values/secrets.xml
          echo "<resources>" >> auth/src/main/res/values/secrets.xml
          echo "    <string name=\"web_client_id\">$WEB_CLIENT_ID</string>" >> auth/src/main/res/values/secrets.xml
          echo "</resources>" >> auth/src/main/res/values/secrets.xml

      # 3. Podbijanie wersji
      - name: Bump Version
        run: python buildSrc/scripts/bump_version.py

      # 4. Commitowanie nowej wersji do repo
      - name: Commit and Push Version Bump
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add buildSrc/src/main/kotlin/ProjectConfig.kt
          git commit -m "CI: Bump version [skip ci]"
          git push

      # 5. Budowanie
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release AAB
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: ./gradlew bundleRelease

      # 6. Wysylanie do Sklepu
      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_CONSOLE_JSON }}
          packageName: com.rafalskrzypczyk.paramedquiz
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal # lub alpha/production
          status: completed # Bezpiecznie: wrzuca jako szkic
